const FriendDummyData = [
	{
		id: 1,
		name: 'Gretel',
		birthday: '2021-11-05',
		wishList: [{}, {}, {}, {}, {}, {}, {}],
		gender: 'Female',
		friendActive: true,
	},
	{
		id: 2,
		name: 'Irvine',
		birthday: '2022-03-21',
		wishList: [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
		gender: 'Male',
		friendActive: true,
	},
	{
		id: 3,
		name: 'Kantor',
		birthday: '2022-06-10',
		wishList: [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
		gender: 'Male',
		friendActive: false,
	},
	{
		id: 4,
		name: 'Marlyn',
		birthday: '2021-03-25',
		wishList: [{}, {}, {}, {}, {}, {}, {}, {}],
		gender: 'Female',
		friendActive: false,
	},
	{
		id: 5,
		name: 'Itch',
		birthday: '2021-08-23',
		wishList: [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
		gender: 'Male',
		friendActive: true,
	},
	{
		id: 6,
		name: 'Reid',
		birthday: '2020-10-28',
		wishList: [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
		gender: 'Bigender',
		friendActive: true,
	},
	{
		id: 7,
		name: 'Libbie',
		birthday: '2021-02-20',
		wishList: [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
		gender: 'Female',
		friendActive: true,
	},
	{
		id: 8,
		name: 'Durward',
		birthday: '2021-02-22',
		wishList: [{}, {}, {}, {}, {}, {}, {}],
		gender: 'Male',
		friendActive: false,
	},
	{
		id: 9,
		name: 'Cissiee',
		birthday: '2022-07-07',
		wishList: [{}, {}, {}, {}],
		gender: 'Female',
		friendActive: true,
	},
	{
		id: 10,
		name: 'Margeaux',
		birthday: '2022-05-06',
		wishList: [{}, {}, {}, {}, {}, {}, {}, {}],
		gender: 'Female',
		friendActive: false,
	},
	{ id: 11, name: 'Bertrand', birthday: '2022-09-22', wishList: [{}], gender: 'Male', friendActive: true },
	{ id: 12, name: 'Brendan', birthday: '2021-07-02', wishList: [{}, {}], gender: 'Male', friendActive: true },
	{
		id: 13,
		name: 'Even',
		birthday: '2022-11-29',
		wishList: [{}, {}, {}, {}, {}, {}, {}],
		gender: 'Male',
		friendActive: true,
	},
	{ id: 14, name: 'McErlaine', birthday: '2021-05-27', wishList: [], gender: 'Male', friendActive: false },
	{
		id: 15,
		name: 'Hamilton',
		birthday: '2022-11-06',
		wishList: [{}, {}, {}, {}],
		gender: 'Male',
		friendActive: false,
	},
	{
		id: 16,
		name: 'Dulsea',
		birthday: '2022-07-21',
		wishList: [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
		gender: 'Female',
		friendActive: true,
	},
	{
		id: 17,
		name: 'Skye',
		birthday: '2022-05-31',
		wishList: [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
		gender: 'Male',
		friendActive: false,
	},
	{
		id: 18,
		name: 'Noble',
		birthday: '2022-04-17',
		wishList: [{}, {}, {}, {}, {}],
		gender: 'Male',
		friendActive: true,
	},
	{
		id: 19,
		name: 'Batsheva',
		birthday: '2023-04-27',
		wishList: [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
		gender: 'Female',
		friendActive: false,
	},
	{
		id: 20,
		name: 'Lezley',
		birthday: '2021-09-03',
		wishList: [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
		gender: 'Male',
		friendActive: false,
	},
	{
		id: 21,
		name: 'Vennard',
		birthday: '2021-06-02',
		wishList: [{}, {}, {}, {}, {}, {}, {}, {}],
		gender: 'Male',
		friendActive: true,
	},
	{ id: 22, name: 'Allys', birthday: '2020-09-08', wishList: [], gender: 'Female', friendActive: true },
	{
		id: 23,
		name: 'Blankley',
		birthday: '2022-05-30',
		wishList: [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
		gender: 'Male',
		friendActive: false,
	},
	{
		id: 24,
		name: 'Killie',
		birthday: '2023-05-10',
		wishList: [{}, {}, {}, {}, {}, {}],
		gender: 'Male',
		friendActive: false,
	},
	{
		id: 25,
		name: 'Debor',
		birthday: '2022-06-02',
		wishList: [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
		gender: 'Non-binary',
		friendActive: false,
	},
	{
		id: 26,
		name: 'Hewitt',
		birthday: '2020-12-10',
		wishList: [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
		gender: 'Genderqueer',
		friendActive: true,
	},
	{
		id: 27,
		name: 'Burt',
		birthday: '2022-09-04',
		wishList: [{}, {}, {}, {}, {}],
		gender: 'Male',
		friendActive: true,
	},
	{
		id: 28,
		name: 'Nikolos',
		birthday: '2021-07-23',
		wishList: [{}, {}, {}, {}, {}, {}, {}, {}],
		gender: 'Male',
		friendActive: false,
	},
	{
		id: 29,
		name: 'Pammi',
		birthday: '2020-09-15',
		wishList: [{}, {}, {}, {}, {}, {}],
		gender: 'Female',
		friendActive: false,
	},
	{
		id: 30,
		name: 'Emby',
		birthday: '2021-08-31',
		wishList: [{}, {}, {}, {}, {}, {}, {}, {}],
		gender: 'Male',
		friendActive: false,
	},
];

export default FriendDummyData;
