const ProductDummyData = [
	{
		id: 1,
		img: '/images/mlbcap.jpg',
		name: 'MLB 모자',
		brand: 'MLB',
		category: '모자',
		price: 39000,
		description: '꽤 괜찮은 모자',
		wished: false,
		inventory: 10,
		viewCnt: 0,
		like: 0,
		entered: false,
		date: '2023-05-07',
	},
	{
		id: 2,
		img: '/images/mlbshirt.jpg',
		name: 'MLB 후드티',
		brand: 'MLB',
		category: '옷',
		price: 79000,
		description: '꽤 괜찮은 후드티',
		wished: false,
		inventory: 50,
		viewCnt: 0,
		like: 0,
		entered: false,
		date: '2023-05-07',
	},
	{
		id: 3,
		img: '/images/airpod3.jpeg',
		name: 'AirPod Pro3',
		brand: 'APPLE',
		category: '악세사리',
		price: 200000,
		description: '애플에서 출시한 에이팟 프로3',
		wished: false,
		inventory: 5,
		viewCnt: 0,
		like: 0,
		entered: false,
		date: '2023-05-07',
	},
	{
		id: 4,
		img: '/images/hal.jpg',
		name: '까스활명수',
		brand: 'COOPSKET',
		category: '음료수',
		price: 700,
		description: '먹으면 속 풀림',
		wished: false,
		inventory: 7,
		viewCnt: 0,
		like: 0,
		entered: false,
		date: '2023-05-07',
	},
	{
		id: 5,
		img: '/images/starbucks.jpeg',
		name: '스타벅스 아메리카노',
		brand: 'STARBUCKS',
		category: '음료수',
		price: 4500,
		description: '너무 써',
		wished: false,
		inventory: 10,
		viewCnt: 0,
		like: 0,
		entered: false,
		date: '2023-05-07',
	},
	{
		id: 6,
		img: '/images/bbq.jpg',
		name: 'BBQ 후라이드 치킨',
		brand: 'BBQ',
		category: '음식',
		price: 20000,
		description: '너무 비싸',
		wished: false,
		inventory: 3,
		viewCnt: 0,
		like: 0,
		entered: false,
		date: '2023-05-07',
	},
];

export default ProductDummyData;
